### ISSUE TITLE
Explore Docker deployment of the packet forwarder

### ISSUE THREAD

**Issue by egourlao** [TheThingsNetwork/packet_forwarder#38]
Since Docker allows to [mount devices in a container](https://stackoverflow.com/questions/24225647/docker-any-way-to-give-access-to-host-usb-or-serial-device), it is possible to mount a concentrator in a container, and thus to run the packet forwarder inside a container.

Deploying the packet forwarder through Docker probably won't be possible for all gateways, since many gateways run stripped-down Linux versions. However, for the ones on which it is possible (such as the Raspberry Pi gateways, combined with iMST concentrators), it can be worthwhile to see how it could be possible to do so. There has already been successful attempts with the previous packet forwarder - such as this [resin.io setup](https://github.com/rayozzie/ttn-resin-gateway-rpi), that deploys the packet forwarder through Docker images. Running the packet forwarder in a container would for example delegate all the operations and start/stop operations to the Docker daemon, without having to maintain systemd/sysv services. This could also allow provisioning and updates through the Docker Hub.

For those who wish to contribute to the packet forwarder, this is an interesting problem to look into to get started - contributions are more than welcome!

**Comment by xenek** [comment]
I used https://github.com/jpmeijers/ttn-resin-gateway-rpi very successfully, with a Raspberry Pi 3.

Now I am using an Odroid XU4. I have no problems running resin.io OS on the XU4 with eMMC, compiling and sending through the application, however I need to get SPI working for the XU4 with Odroid Shifter Shield before I can see if my risingHF hardware is working with the shifter shield. 

(I am pretty sure I am the first to try using an Odroid XU4 & Shifter Shield & Rising HF RHF4T002 & Rising HF RHF0M301) 

The RPI version of the gateway by jpmeijers can't use the XU4 SPI ports due to the different architecture / missing / alternative libraries.

So, I have put aside resin.io and docker and instead started building the new TTN gateway packet forwarder manually on the XU4 in Ubuntu 16.04.02 LTS. 

If I can get it working running with this particular 4-stack hardware setup, I'll try using Docker. 
If I can get it working in Docker, I'll try using resin.io.
